services:
  db:
    ports:
      - 8001:5432
    container_name: postgresql_container
    image: postgres
    entrypoint:
      - POSTGRES_DB = STUDYDB2
      - POSTGRES_PASSWORD = admin2
      - POSTGRES_USER=admin2
    volumes:
      - C:\Users\miurovskaia\Documents\study_postgres_datapart:/var/lib/postgresql/data
    restart: always
  backend:
    build: .
    container_name: testapp_container
    ports:
      - 8089:8089
    environment:
      db-url: jdbc:postgresql://db:5432/STUDYDB2
      db-username: admin2
      db-password: admin2
    depends_on:
      - db
    restart: always


