version: "3.8"

services:

  db:
    image: postgres:14.1-alpine
    #image: devbeta/postgres:9.6.9
    container_name: postgres
    restart: always
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db
    ports:
      - "5432:5432"

volumes:
  db-data: